let express=require("express")
const { getall, getcat, addpost, getpost, upd, del, pdm, inspect, accept, admin, like, dlike, addcomm, delcom } = require("../Controllers/postCont")
const { isLogin, isAdmin, adduser, login } = require("../Controllers/userCont")
const { sendOtp, updatePwd } = require("../Controllers/resetpwdCont")
let rt=express.Router()
rt.get("/getall",getall)
rt.get("/getcat/:cat",getcat)
rt.get("/getpost/:pid",getpost)
rt.post("/addpost",addpost)
rt.post("/reg",adduser)
rt.post("/login",login)
rt.put("/update",upd)
rt.get("/pdm/:uid",pdm)
rt.delete("/del/:pid",del)
rt.get("/admin",admin)
rt.put("/inspect",inspect)
rt.put("/accept/:pid",accept)
rt.put("/like",like)
rt.put("/dlike",dlike)
rt.get("/getotp/:uid",sendOtp)
rt.put("/updpwd",updatePwd)
rt.put("/addcomm",addcomm)
rt.put("/delcom",delcom)
module.exports=rt